# docker-compose.yml
version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: videojuegos-db
    restart: always
    environment:
      MYSQL_DATABASE: videojuegos_db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      # Esto ejecuta tu script init.sql al crear la BD por primera vez
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: videojuegos-backend
    restart: always
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=videojuegos_db
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: videojuegos-frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend