name: CI/CD Pipeline Videojuegos

on:
  push:
    branches: ["main"]

env:
  AWS_REGION: us-east-1
  ECR_FRONTEND_REPOSITORY: videojuegos-frontend
  ECR_BACKEND_REPOSITORY: videojuegos-backend
  ECS_CLUSTER: videojuegos-cluster
  ECS_SERVICE: videojuegos-service
  ECS_TASK_DEFINITION: task-definition.json

jobs:
  test:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install backend deps
        working-directory: backend
        run: npm install 

      - name: Run tests
        working-directory: backend
        run: npm test

  build-push-deploy:
    name: Build, Push & Deploy to ECS
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} 
          aws-region: ${{ env.AWS_REGION }}

          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push backend image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f backend/Dockerfile -t $ECR_REGISTRY/${{ env.ECR_BACKEND_REPOSITORY }}:$IMAGE_TAG backend
          docker push $ECR_REGISTRY/${{ env.ECR_BACKEND_REPOSITORY }}:$IMAGE_TAG

      - name: Build and push frontend image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f frontend/Dockerfile -t $ECR_REGISTRY/${{ env.ECR_FRONTEND_REPOSITORY }}:$IMAGE_TAG frontend
          docker push $ECR_REGISTRY/${{ env.ECR_FRONTEND_REPOSITORY }}:$IMAGE_TAG

      - name: Inject Variables into Task Definition
        run: |
          sed -i "s/AWS_ACCOUNT_ID/${{ secrets.AWS_ACCOUNT_ID }}/g" ${{ env.ECS_TASK_DEFINITION }}
          sed -i "s/<ENDPOINT_DE_TU_BASE_DE_DATOS>/${{ secrets.DB_ENDPOINT }}/g" ${{ env.ECS_TASK_DEFINITION }}

      - name: Render Backend Image in Task Definition
        id: render-backend
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: backend
          image: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_BACKEND_REPOSITORY }}:${{ github.sha }}
          environment-variables: |
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}

      - name: Render Frontend Image in Task Definition
        id: render-frontend
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ steps.render-backend.outputs.task-definition }}
          container-name: frontend 
          image: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_FRONTEND_REPOSITORY }}:${{ github.sha }}

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-frontend.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true